name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript type checking
        run: npm run type-check

      - name: Run ESLint
        run: npm run lint

      - name: Build project
        # Use dummy environment variables to prevent key validation during CI
        env:
          NEXT_PUBLIC_CONVEX_URL: "https://dummy.convex.cloud"
          UPSTASH_REDIS_REST_URL: "https://dummy.upstash.io"
          UPSTASH_REDIS_REST_TOKEN: "dummy_token"
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: "pk_test_cmVsYXhlZC1zdW5maXNoLTAuY2xlcmsuYWNjb3VudHMuZGV2JA"
          CLERK_SECRET_KEY: "sk_test_dummy"
          CLERK_FRONTEND_API_URL: "https://dummy.clerk.accounts.dev"
          CLERK_JWT_ISSUER_DOMAIN: "dummy.clerk.accounts.dev"
          NEXT_PUBLIC_RAZORPAY_KEY_ID: "rzp_dummy"
          RAZORPAY_KEY_SECRET: "dummy_secret"
          RESEND_API_KEY: "re_dummy"
          FROM_EMAIL: "dummy@example.com"
          TO_EMAIL: "dummy@example.com"
          GOOGLE_SHEETS_SPREADSHEET_ID: "dummy_spreadsheet_id"
          GOOGLE_SHEETS_SHEET_NAME: "Sheet1"
          GOOGLE_APPLICATION_CREDENTIALS_JSON: "{}"
          SENTRY_AUTH_TOKEN: "dummy_token"
          NODE_ENV: "production"
          NEXT_PUBLIC_CLERK_SIGN_IN_URL: "/sign-in"
          NEXT_PUBLIC_CLERK_SIGN_UP_URL: "/sign-up"
          NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: "/"
          NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL: "/"
          CLERK_SKIP_KEY_VALIDATION: "true"
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: build-artifacts
          path: .next/
          retention-days: 7
